<?php
/**
 * @file
 * Code for the Announcements feature.
 */

include_once 'announcements.features.inc';

/**
 * Implements hook_views_pre_render().
 */
function announcements_views_pre_render(&$view) {
  $people_view = array('announcements', 'announcements');
  if (in_array($view->name, $people_view)) {
    //drupal_add_js(drupal_get_path('module', 'td_deals') . '/td_deals.js');
    $people_module_path = drupal_get_path('module', 'announcements');
    //drupal_add_js($contextual_module_path . '/contextual.js');
    drupal_add_css($people_module_path . '/css/announcements.css');
  }
}

/**
 * Implements hook_update_projects_alter().
 */
function announcements_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['announcements']);
}