<?php
/**
 * @file
 * Code for the Announcements feature.
 */

include_once 'announcements.features.inc';

/**
 * Implements hook_update_projects_alter().
 */
function announcements_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['announcements']);
}

/**
 * Implements hook_views_pre_render().
 */
function announcements_views_pre_render(&$view) {
  $announcements_view = array('announcements', 'announcements');
  if (in_array($view->name, $announcements_view)) {
    //drupal_add_js(drupal_get_path('module', 'td_deals') . '/td_deals.js');
    $announcements_module_path = drupal_get_path('module', 'announcements');
    //drupal_add_js($contextual_module_path . '/contextual.js');
    drupal_add_css($announcements_module_path . '/css/announcements.css');
  }
}


// Adds CSS to view display of announcements node type but not the edit display
function announcements_preprocess_page(&$vars) {
  // Global node.
  $node = menu_get_object();
  if (!empty($node) && $node->type == 'announcements' && arg(2) === null) {
    drupal_add_css(drupal_get_path('module', 'announcements') . '/css/announcements.css');
  }
}

// Adding support to discover template files
/**
 * Implements hook_theme_registry_alter()
 **/
function announcements_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'announcements');
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _announcements_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
 */
function _announcements_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}